// export const SERVER_LOCATION = process.env.NODE_ENV === 'development' ? 'http://localhost:5000/' : 'https://xoma-star.space/'
export const SERVER_LOCATION = 'https://xoma-star.space/'
export const FILES_LOCATION = SERVER_LOCATION + 'media/'
export const TRACK_DATA_LOCATION = SERVER_LOCATION + 'tracks/'
export const PLAYLIST_DATA_LOCATION = SERVER_LOCATION + 'playlist/'
export const USER_DATA_LOCATION = SERVER_LOCATION + 'users/'
export const AUTH_LOCATION = SERVER_LOCATION + 'auth/'